name: Deploy EDA with Serverless Framework

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '22.10.0'

    # Serverless y dependencias
      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Install Serverless Framework python-requirements
        run: npm install -g serverless-python-requirements

      - name: Install Serverless Framework scriptable-plugin
        run: npm install -g serverless-scriptable-plugin

      - name: Install dependencies
        run: npm install

      # AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1 

      # Deploy
      - name: Deploy with Serverless
        run: serverless deploy --stage dev --verbose
